### ISSUE TITLE
Re-structure User Guide into Concepts, Tasks & Reference

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform-user-guide#37]
This is a suggestion from Adrian Warman, when I consulted him for some advice
on how we could structure our user guide.

He suggested a common structure based on 3 top-level sections:

## Concepts

This section consists of background that the reader would need in order to
understand the overall structure of the Cloud Platform, and descriptions of the
high-level concepts involved. Examples of things to put here would be:

 * What is kubernetes?
 * Cloud Platform roadmap
 * High-level view of our build pipelines
 * Digram & description of the components of the Cloud Platform

## Tasks

Task-oriented tutorials and articles which users can work through in order to
achieve a specific outcome. Examples of these could include:

 * How to create an ECR
 * How to create a namespace
 * How to create and use and RDS instance
 * How to deploy an application

The 'Tasks' section is likely to contain most of the content of the user guide.

We may or may not need a 'Reference' section, initially.

Once this structure is in place, existing content should be migrated into the
new structure, making any required changes (e.g. an existing item might have
some content that belongs in Concepts, and some that belongs in Tasks).

## Definition of done

 - [ ] All existing user guide content is moved into an "Archive" section
 - [ ] There is a notice on the first page explaining that the guide is being restructured
 - [ ] There are top-level "Concepts" and "Tasks" sections
 - [ ] There is at least one content item in each of the Concepts and Tasks sections
